server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-springboot-learn?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长
      minimum-idle: 5           # 最小连接数
      maximum-pool-size: 20     # 最大连接数
      auto-commit: true         # 自动提交
      idle-timeout: 600000      # 连接超时的最大时长
      pool-name: DateSourceHikariCP #连接池名字
      max-lifetime: 1800000 # 连接的生命时长
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 2MB
  banner:
    image:
      location: classpath:banner.txt
# mybatis 配置
mybatis:
  type-aliases-package: com.imooc.pojo       # 逆向解析存放的实体类Entity
  mapper-locations: classpath:mappers/*.xml  # 所有mapper映射的文件所在目录位置
#通用mapper 配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
# 分页助手配置
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql
